table 'Seller Lookup'
	lineageTag: edc81742-12b5-4244-bd37-e6223ca33771

	column SellerKey
		dataType: int64
		formatString: 0
		lineageTag: 92b1b772-141a-4b4b-b432-0f565c6b68e4
		summarizeBy: count
		sourceColumn: SellerKey

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column Seller_ID
		dataType: string
		lineageTag: 4bc15a36-7bef-4f4e-9c93-1cc518cd647c
		summarizeBy: none
		sourceColumn: Seller_ID

		annotation SummarizationSetBy = Automatic

	column GeographyKey
		dataType: int64
		isHidden
		formatString: 0
		lineageTag: 233efb60-60a3-4d46-b369-120d639322c1
		summarizeBy: none
		sourceColumn: GeographyKey

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	partition 'Seller Lookup' = m
		mode: import
		source =
				let
				  Source = MySQL.Database("127.0.0.1", "olist_bi"),
				  #"Navigation 1" = Source{[Schema = "olist_bi", Item = "dim_seller"]}[Data],
				    #"Removed Columns" = Table.RemoveColumns(#"Navigation 1",{"olist_bi.dim_geography", "olist_bi.fact_orderitems"})
				in
				  #"Removed Columns"

	annotation PBI_ResultType = Table

	annotation PBI_NavigationStepName = Navigation

